name: ard
description: "Mirror Blog Radhitya"
url: "https://mirror.radhitya.mengobrol.com"

links:
  mastodon: https://mastodon.social/@radhitya

paginate: 10
permalink: /:title.html

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
      css_class: 'highlight'

sass:
  style: :expanded

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

feed:
  posts_limit: 100

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - drafts
  - posts
  - BACKUP
  - config.yml
  - drafts
  - drafts_backup
  - "00-ÖVERSÄTTA"

include: ['_pages', '_pages/bookmarks']
exclude: ['drafts', 'posts', '00-ÖVERSÄTTA']
