name: radhitya
description: "meaningless blog"
url: "https://radhitya.mengobrol.com"

paginate: 5
permalink: /:title
paginate_path: "/weblog/page:num/"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
      css_class: 'highlight'
feed:
  path: atom.xml
  posts_limit: 2020

sass:
  style: :expanded

jekyll-archives:
  enabled:
    - categories
  layout:
    category: arsip
  permalink: 
    categories: '/arsip/categories/:name/'
  slug_mode: latin

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives

feed:
  posts_limit: 100

exclude:
  - pages
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - drafts
  - posts
  - BACKUP
  - config.yml
  - drafts
  - drafts_backup
  - "00-ÖVERSÄTTA"

include: ['_pages',]
exclude: ['drafts', 'posts', '00-ÖVERSÄTTA']
